print("Welcome to the world of programming with python this will be a interesting experince")
print("The journery is based on your story and you will be asked a series of questions to hell you create a unique epic story")
print()
name = input("What is your name:?")
age = input("What is your age:?")
skills = input("What are your skills:?")
coding = input("For how long have you been coding:?")
projects = input("What projects have you worked on:?")
print()
print(
"Hello",name,"you are",age,"years old and you have been coding for",coding,"\033[34m years and you have worked on \033[0m" ,projects,"projects")