print("Getting to know your")

userName = input("What's your name?:")
userFood = input("What's your favourite food?:")
userMusic = input("What's your favourite music?:")
userArea = input("Where do you live?:")
print()
print()
print("You are")
print(userName)
print("You're probably hungry for")
print(userFood)
print("and you're definitely getting your groove on to")
print(userMusic)
print("living in the amazing")
print(userArea)